## Neuron with 3 inputs

In [2]:
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2 
output  = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

print(output)


2.3


## Neuron with 4 inputs


In [3]:
inputs = [1.0,2.0,3.0,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2.0

output  = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

4.8


In [9]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2,0.8,-0.5,1.0], #Weights associated with the first neuron
           [0.5,-0.91,0.26,-0.5], #Weights associated with the second neuron
           [-0.26,-0.27,0.17,0.87]] #Weights associated with the third neuron

biases = [2,3,0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [ #Neuron1 output-
            inputs[0]*weights[0][0]+
            inputs[1]*weights[0][1]+
            inputs[2]*weights[0][2]+
            inputs[3]*weights[0][3]+ bias1,

            #Neuron2 output-
            inputs[0]*weights[1][0]+
            inputs[1]*weights[1][1]+
            inputs[2]*weights[1][2]+
            inputs[3]*weights[1][3]+ bias2,

            #Neuron3 output-
            inputs[0]*weights[2][0]+
            inputs[1]*weights[2][1]+
            inputs[2]*weights[2][2]+
            inputs[3]*weights[2][3]+ bias3 ]
print(outputs)
            

[4.8, 1.21, 2.385]


In [11]:
inputs = [1.1,2.2,3.3]

weights = [[2,0,0],
           [2,2,0],
           [2,2,2]]
biases = [0,0,1]

layer_output = []

for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output = 0 
    for neuron_input, weight in zip(inputs, neuron_weights):
        neuron_output += neuron_input*weight 
    neuron_output += neuron_bias
    layer_output.append(neuron_output)

print(layer_output)

[2.2, 6.6000000000000005, 14.2]


In [12]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2,0.8,-0.5,1.0], 
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]] 

biases = [2,3,0.5]

layer_output = []

for neuron_weights,neuron_bias in zip(weights,biases):
    neuron_output = 0 
    for neuron_input, weight in zip(inputs, neuron_weights):
        neuron_output += neuron_input*weight 
    neuron_output += neuron_bias
    layer_output.append(neuron_output)

print(layer_output)

[4.8, 1.21, 2.385]


In [6]:
import numpy as np
X = [1,2,3, 2.5]
W = [0.2,0.8,-0.5,1.0]
bias = 2 
output1 = np.dot(X,W) + bias
output2 = np.dot(W,X) + bias

print(output1)
print(output2)

4.8
4.8


In [14]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2,0.8,-0.5,1.0], 
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]] 

biases = [2,3,0.5]

layer_output = np.dot(weights,inputs) + biases
print(layer_output)

[4.8   1.21  2.385]


In [17]:
#Inputs
X = [[1.0,2.0,3.0,2.5],
     [2.0,5.0,-1.0,2.0],
     [-1.5,2.7,3.3,-0.8]]
#Weights
W = [[0.2,0.8,-0.5,1.0], 
     [0.5,-0.91,0.26,-0.5],
     [-0.26,-0.27,0.17,0.87]] 

biases = [2.0,3.0,0.5]

batch_output = np.dot(X,np.array(W).T) + biases

print(batch_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [19]:
#Inpu Layer
X = [[1.0,2.0,3.0,2.5],
     [2.0,5.0,-1.0,2.0],
     [-1.5,2.7,3.3,-0.8]]
#Weights1
W1 = [[0.2,0.8,-0.5,1.0], 
     [0.5,-0.91,0.26,-0.5],
     [-0.26,-0.27,0.17,0.87]] 
#Bias of first hidden layer
bias1 = [2.0,3.0,0.5]

#Weights2
W2 = [[0.1,-0.14,0.5], 
     [-0.5,0.12,-0.33],
     [-0.44,0.73,-0.13]] 

#Bias of second hidden layer
bias2 = [-1,2,-0.5]

X = np.array(X)
W1 = np.array(W1)
bias1 = np.array(bias1)
W2 = np.array(W2)
bias2 = np.array(bias2)

output_1 = np.dot(X,W1.T) + bias1

output_2 = np.dot(output_1,W2.T) + bias2

print(output_2)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


# Homework


In [24]:
X = [ 1.40 ,-0.80 ,2.30, 0.70, -1.50 ]


#First hidden layer
W1 = [  [ 0.72, -0.51 ,1.03 ,0.28 ,-0.44 ],
        [-0.89 ,0.64 ,-0.37 ,1.12, 0.45 ],
        [ 1.21, -0.29, 0.56, -0.88, 0.62 ],
        [ 0.18, 0.94 ,-1.14 ,0.37,-0.59 ],
        [-0.67, 0.52 ,0.31 ,-0.76, 1.05 ],
        [ 0.91 ,-0.73 ,0.15 ,0.83, -0.22 ],
        [-0.16 ,0.34 ,-0.97, 0.26, 0.79 ],
        [ 0.57 ,-1.01 ,0.41, -0.48, 0.63 ]  ]

b1 = [0.24, -0.51, 0.87, -0.19, 0.42, -0.73, 0.16, 0.95]


#Second hidden layer
W2 = [  [0.44, -0.81, 0.29, 0.73, -0.55, 1.12, -0.36, 0.95],
        [-0.47, 0.62, 0.84, -0.28, 0.67, -0.13, 1.09, -0.71],
        [0.25, 0.48, -0.92, 0.31, -0.64, 1.15, -0.19, 0.77],
        [0.56, 0.82, -0.22, -0.48, 0.93, -0.61, -0.74, 0.58],
        [0.41, -0.35, 1.17, 0.26, 0.21, -1.03, 0.75, 0.14],
        [-0.87, 0.69, 0.98, 0.27, -0.58, 0.86, 0.33, -0.92]  ] 

b2 = [-0.38, 0.61, 0.14, -0.82, 0.47, 0.29]


#Third hidden layer
W3 = [  [0.63, -0.45, 0.91, -0.26, -0.57, 1.08],
        [-0.34, 0.72, 0.82, 0.19, -0.77, 1.14],
        [-0.29, 0.66, 0.53, -0.88, 1.03, -0.52],
        [0.38, 0.25, -0.71, 0.47, -1.11, 0.84]  ]

b3 = [0.35, -0.67, 0.92, -0.21]


#Fourth hidden layer
W4 = [  [0.87, -0.41, 0.68, -0.62],
        [1.15, -0.29, 0.34, -0.97],
        [0.83, 1.06, 0.25, -0.74]  ]

b4 = [-0.44, 0.73, 0.18]

#Converting each list into numpy array
X = np.array(X)
W1 = np.array(W1)
b1 = np.array(b1)

W2 = np.array(W2)
b2 = np.array(b2)

W3 = np.array(W3)
b3 = np.array(b3)

W4 = np.array(W4)
b4 = np.array(b4)

output_layer1 = np.dot(X,W1.T) + b1
output_layer2 = np.dot(output_layer1,W2.T) + b2
output_layer3 = np.dot(output_layer2, W3.T) + b3
output_layer4 = np.dot(output_layer3, W4.T) + b4

print(output_layer4)


[13.30533122 18.30253107 -2.47711351]
